apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ui
    version: v1
  name: ui
spec:
  selector:
    matchLabels:
      app: ui
      version: v1
  template:
    metadata:
      labels:
        app: ui
        version: v1
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/lsteck-tekton-argocd/app:f1eeae4
        imagePullPolicy: Always
        name: ui
        ports:
        - containerPort: 3000
